//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        internal int id;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.LIVROS = new HashSet<LIVROS>();
        }
    
        public int Id_Cliente { get; set; }
        public string RG { get; set; }
        public string Nome_Cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIVROS> LIVROS { get; set; }
    }
}
