//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVROS
    {
        internal static List<LIVROS> DataSource;

        internal static void DataBind()
        {
            throw new NotImplementedException();
        }

        internal readonly int id;
        internal string descricao;

        public int Id_Livro { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public string Desc_Livro { get; set; }
        public string Autor_livro { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
